### PR TITLE
Addressing arithmetic methods for sciTensors

### PR DESCRIPTION
**Pull request by kwhitehall**
- allow scalar operations for +,-,*,/
- allow in-place and copy operations

### CODE REVIEW

**Comment by kwhitehall** [comment]
Can someone please review this commit? @rahulpalamuttam @chrismattmann @BrianWilson1

**Comment by chrismattmann** [comment]
Overall I am +1 for this PR, but I would prefer we replace the System.out.println with logging.

**Comment by kwhitehall** [comment]
Ack'ed @chrismattmann, I'll update accordingly.

**Comment by kwhitehall** [comment]
Done.

**Pull request merged**
