### PR TITLE
[SCISPARK 79] Refactoring BasicTensorTests

### PR DESCRIPTION
**Pull request by rahulpalamuttam**
Took out the tests that involed RDD's and moved them to RDDIntegrationTest under:
/src/test/scala/org/dia/integration

This way we can unit test simple linear algebra operations without having to wait
on the sparkcontext to be instantiated, find a port, etc.

### CODE REVIEW

**Comment by rahulpalamuttam** [comment]
In reference to issue #79 

@kwhitehall @chrismattmann @BrianWilson1 

Feel free to comment on any additional things to do towards organizing the tests.

**Comment by kwhitehall** [comment]
Hi @rahulpalamuttam, thanks for the efforts here, however I'm not certain I follow this refactoring suggestion. The sciTensor is a user-defined data element within the (s)RDD, so when testing any functionality related to it, it seems prudent to test it within the (s)RDD. Hence the unit test should be for the linear algebra operations working on the sciTensors as opposed to on arrays. These test should remain within the tensor tests IMO. Further, RDDIntegration test should refer to any unit test associated with extending the (s)RDD. Can you please expound on your reasoning for this suggested refactoring?

**Comment by rahulpalamuttam** [comment]
Hi @kwhitehall,

As discussed I've moved the tests involving (s)RDD's into SRDDTest.
I think the only thing left is to add tests for SciTensor by itself.
However, it looks like we have some more ongoing discussion about SciTensor and I feel that needs to be resolved first. In anycase the SRDDTest class takes care of the SciTensor tests as well for now.

**Comment by chrismattmann** [comment]
LGTM, merged 👍

**Pull request merged**
