### PR TITLE
Scispark-61 generating the openDap urls

### PR DESCRIPTION
**Pull request by kwhitehall**

### CODE REVIEW

**Comment by kwhitehall** [comment]
Still working on this PR.

**Comment by chrismattmann** [comment]
LGTM as a start. @kwhitehall

**Comment by kwhitehall** [comment]
Ok @chrismattmann and @rahulpalamuttam 
I think I'm finished with this PR. 
To run the unit test, from command line the following is required
SBT_OPTS="-DhdfsURL=hdfs://url_host:port" sbt "test-only org.dia.urlgenerators.OpenDapTRMMURLGeneratorTest"

TODO: is to get the thread / waiting between calls to the openDap server in the SciSparkContext.scala line 106 going.

Finally, this PR addresses issue #61 and #67 (indirectly - the openDap and any url from file will now be read into a rdd of SciTensors)

**Comment by chrismattmann** [comment]
LGTM +1 to commit. @kwhitehall @rahulpalamuttam

**Comment by kwhitehall** [comment]
Ack'ed @chrismattmann. Thanks!

**Pull request merged**
