### PR TITLE
Some minor review + cleanup, to get familiar with the code

### PR DESCRIPTION
**Pull request by ghost**
- generated files for eclipse (.project/classpath/settings folders) to recognize it as sbt project
- reviewed org.dia.tensors package but didn't change anything significant there
- got rid of sbt compile warnings by adding joda-convert dependency to build.sbt

### CODE REVIEW

**Comment by chrismattmann** [comment]
thanks @legendOfZelda - this is a huge patch and contains binary files and project specific entries that not all of our developers will want to inherit automatically. Can you pull out ht parts about getting rid of compile warnings, and also any code updates and submit those as an update to this PR? As it stands it contains over 500 file changes and I can't even full review it. Thank you.

**Comment by ghost** [comment]
oops, sry. now it should be fine

**Comment by chrismattmann** [comment]
ok almost there @legendOfZelda . Everything looks great! Can you remove the:
- .settings
- .classpath
- .project

from the PR? These are developer specific and shouldn't be checked in. At that point I think we can merge. cheers

**Comment by ghost** [comment]
@chrismattmann - ok, removed those. didnt think that not everybody necessarily wants to use eclipse. and even if we all use eclipse each one of us might have different eclipse project configurations, yes.

**Comment by chrismattmann** [comment]
awesome merging @legendOfZelda thanks!

**Pull request merged**
