### PR TITLE
default constructor for SciSparkContext takes the SparkContext

### PR DESCRIPTION
**Pull request by rahulpalamuttam**
This pull request changes the default SciSparkContext to take the SparkContext.
This enables interoperability with Zeppelin which provides its own context.

### CODE REVIEW

**Comment by chrismattmann** [comment]
Thanks @rahulpalamuttam - @legendOfZelda I'd like you to review before this is merged.

**Comment by rahulpalamuttam** [comment]
Looks like intellij has a different javadoc commenting style - it inserts a space at the start of each javadoc line. Also I uncommented the <= function abstract tensor, so it can be used to mask values.

**Comment by ghost** [comment]
ok, i will have this reviewed today, let you know when done

**Comment by ghost** [comment]
left todo before merge:
- use map in Nd4jTensor everywhere else where needed and uncomment the
  "@todo not implemented yet because Nd4j lib does not provide map yet"
- put nd4s into build.sbt explicitly. the 'map' worked without explicitly importing nd4s in build.sbt because it probably did it behind the scenes realizing it needed it, but i think its better to download it through the build.sbt explicitly

**Comment by rahulpalamuttam** [comment]
I have uncommented map in nd4jtensor.
ND4S was specifically left out in the dependency list in build.sbt since at the time it didn't have a maven central repo and it needed to be constantly cloned and installed to local maven repo. 
Also the api wasn't that stable. 

The latest commit includes the latest version of nd4s, and consequently the latest the version of nd4j (0.4-rc3.8). Having mixed versions of nd4s and nd4j resulted in interesting classnotfound errors with Nd4jFactory. 

I also removed the nd4s jar from lib. However I left the lib directory and the 2 lines of code in sbt that looks at the lib directory for unmanaged jars. My thought is to allow people to include jars in custom builds or try out new libraries that have not been submitted to maven central when working with SciSpark. Not too sure if that is reason enough to keep an empty directory. Otherwise we can just remove it and update the build.sbt

**Comment by rahulpalamuttam** [comment]
Done - removed those todo statements

**Comment by ghost** [comment]
ok, this can be merged @chrismattmann

**Comment by kwhitehall** [comment]
Thanks @rahulpalamuttam  and @legendOfZelda! !@chrismattmann we were able to test. Feel free to merge away.

**Comment by chrismattmann** [comment]
i'll go ahead and merge this. thanks! @kwhitehall @legendOfZelda @rahulpalamuttam

**Pull request merged**
